config/routes.rb
Rails.application.routes.draw do
  resources :forgotpasswords
  resources :relationships
  resources :twitzs
 resources :sessions
  resources :users

  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'friends', to: 'users#friends', as: 'friends'

  root to: "users#new"

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  attr_accessible :follower_id, :followed_id

  belongs_to :follower, class_name:'User'
  belongs_to :followed, class_name: 'User'
end

app/models/twitz.rb
class Twitz < ActiveRecord::Base
  attr_accessible :content, :user_id
  default_scope {order("created_at DESC")}

  belongs_to :user

  validates :content, length: { maximum: 140 }
end

app/models/user.rb
require "digest/md5"
class User < ActiveRecord::Base
  attr_accessible :name, :username, :password, :password_confirmation, :bio, :avatar_url, :email
  has_secure_password

  has_many :twitzs
  has_many :follower_relationships, class_name:'Relationship', foreign_key:'followed_id'
  has_many :followed_relationships, class_name:'Relationship', foreign_key:'follower_id'
  has_many :followers, through: :follower_relationships
  has_many :followeds, through: :followed_relationships
  before_validation :prep_email
  before_save :create_avatar_url

  validates :email, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true
  validates :name, presence: true

  def following? user
     self.followeds.include? user
  end
  def follow user
    Relationship.create follower_id: self.id, followed_id: user.id
  end


  private
  def prep_email
    self.email = self.email.strip.downcase if self.email
  end

  def create_avatar_url
    self.avatar_url = "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(self.email)}?s=50"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/forgotpasswords_controller.rb
class ForgotpasswordsController < ApplicationController
  def create
    user = User.find_by(email: params[:email].downcase)
    if user
      @userp = user.password
      UserNotifier.reset_email(user).deliver_now
      redirect_to forgotpasswords_path, notice: "password Recovered!!."
    else
        flash[:error] = "Wrong Email id."
        redirect_to forgotpasswords_path
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    relationship = Relationship.new(params[:relationship])
    relationship.follower = current_user

      flash[:error] = "Couldn't Follow" unless relationship.save
      redirect_to relationship.followed
  end

  def destroy
    relationship = Relationship.find(params[:id ])
    user = relationship.followed
    relationship.destroy
    redirect_to user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_email params[:email]
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to current_user, notice: "Logged In!."
    else
        flash[:error] = "Wrong username and password."
        redirect_to root_url
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out."
  end
end

app/controllers/twitzs_controller.rb
class TwitzsController < ApplicationController
    def index
      @twitzs = Twitz.all
      @twitz = Twitz.new
    end

    def create
      twitz= Twitz.new(params[:twitz])
      twitz.user_id = current_user.id

      flash[:error] = "Your twitz was over 140 characters " unless twitz.save
      redirect_to root_url
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    if current_user
      redirect_to friends_path
    else
        @user = User.new
    end
  end

  def create
     @user = User.new(params[:user])
      if @user.save
        session[:user_id] = @user.id
        UserNotifier.welcome_email(@user).deliver_now
        redirect_to @user , notice: "Thank you for signing up"
      else
          render 'new'
      end
  end

  def index
    @users = User.all
    @twitz = Twitz.new
  end

  def friends
    if current_user
      @twitz = Twitz.new
      friends_ids = current_user.followeds.map(&:id).push(current_user.id)
      @twitzs = Twitz.where(user_id: friends_ids)
    else
      redirect_to root_url
    end

  end

  def show
    @user = User.find_by_id(params[:id])
    @twitz = Twitz.new
    @relationship =  Relationship.where(
      follower_id: current_user,
      followed_id: @user.id
      ).first_or_initialize if current_user
  end

  def edit
    @user = User.find(params[:id])
    redirect_to @user unless @user == current_user
  end
  def update
     @user = User.find(params[:id])
     if @user.update_attributes(params[:user])
       redirect_to @user, notice: "Profile Updated!!"
     else
       render 'edit'
     end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forgotpasswords_helper.rb
module ForgotpasswordsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/twitzs_helper.rb
module TwitzsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/forgotpasswords/forgotpassword.html.erb
<div class="container">
  <div class="row">
    <div class="forgot">
      <h1>FORGOT PASSWORD</h1>
    </div>
  </div>
</div>

app/views/forgotpasswords/index.html.erb
<div class="container">
  <div class="row">
    <div class="forgot text-center">
      <h1 class="c-white">FORGOT PASSWORD</h1>
      <div class=" col-sm-offset-3 col-sm-6">
        <%= form_tag forgotpasswords_path do %>
            <%= text_field_tag :email, nil, placeholder: "email", :class=>"form-control",:required => true%>
        <%= submit_tag 'Password Reset',:class=>"btn btn-success marg-5" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TWITZNEPAL</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navigation">
    <nav class="navbar navbar-default" role="navigation">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
             <%if current_user %>
           <%= link_to image_tag('logo.png'), friends_path,:class=>"navbar-brand c-white"%>
           <% else %>
            <%= link_to image_tag('logo.png'), root_url,:class=>"navbar-brand c-white"%>
           <% end %>
         </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav navbar-right">
              <%if current_user %>
                <li> <%= link_to "My-Profile", current_user, :class => "c-white"  %></li>
                <li><%= link_to "Friends' Twitz", friends_path, :class => "c-white" %></li>
                <li><%= link_to "Public Profile", users_path, :class => "c-white" %></li>
                  <li><%= link_to "Public Twitzs", twitzs_path, :class => "c-white" %></li>
                  <li><%= link_to("Log Out",logout_path, :class => "c-white") %></li>
                  <form class="navbar-form navbar-right" role="search">
                    <div class="form-group">
                      <input type="text" class="form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-danger">Submit</button>
                  </form>
              <%else %>
                <div class="form-inline">
              <%= form_tag sessions_path do %>
                  <%= text_field_tag :email, nil, placeholder: "email", :class=>"form-control",:required => true%>
                  <%= password_field_tag :password, nil, placeholder: "password", :class=>"form-control",:required => true%>
                  <%= submit_tag "Login", :class =>"btn btn-primary" %><br>
              <%end %>
                <%= link_to("Forgot Password!!",forgotpasswords_path, :class =>"pull-right c-white") %>
                <% end %>
            </div>
          </ul>
          <div class="clearfix"></div>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
  </div>
  <div class="container">
      <% flash.each do |name, msg| -%>
        <%= content_tag :div, msg, class: name %>
      <% end -%>
  </div>
 <%= yield %>
<footer class="c-white text-center">
    COPYRIGHT All Right Reserved!!TWITZNEPAL &copy;<%= Date.today.year %>
</footer>
  <!-- Latest compiled and minified JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/js/bootstrap.min.js"> </script>
</body>
</html>

app/views/twitzs/index.html.erb
<div class="show">
  <div class="container">
    <div class="col-md-6">
      <div class="show-prof">
        <h2> Public Twitz</h2>
        <% @twitzs.each do |twitz| %>
          <a href=" <%= user_path twitz.user %>">
            <img src="<%= twitz.user.avatar_url%>" class="img-responsive" alt="Image">
            <span><%= twitz.user.name %></span>
          </a>
          <span>@<%= twitz.user.username %></span>
          <span class="time"><%= time_ago_in_words(twitz.created_at) %>&nbsp;ago</span>
          <p>
            <%= twitz.content %>
          </p>
        <% end %>
        <!-- <div class="panel left">
          <h2>Your Twitz</h2>

        </div> -->
      </div>
    </div>
   <% if current_user %>
    <div class="col-md-offset-2 col-md-3">
      <h2>Create a Twitz</h2>
      <p>
        <%= form_for @twitz do |t| %>
        <%= t.text_area :content, :id=>"twitztxt",:class=>"text-area", :required=> true%>
        <%= t.submit "Twitz!!!", :class=>"btn btn-success marg-5", :id=> "twitzbtn" %>
        <span class="c-white" id="CharCount">0</span>
        <% end %>
      </p>
    </div>
    <% end %>
  </div>
</div>
<%= javascript_include_tag 'twitzs' %>

app/views/user_notifier/reset_email.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
</head>
<body>
  <h1>Welcome to Twitznepal.com, <%= @user.name %></h1>
  <p>
    your password is: <%= @userp%>
  </p>
  <p>Your password has been recovered!</p>
</body>
</html>

app/views/user_notifier/welcome_email.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
</head>
<body>
  <h1>Welcome to Twitznepal.com, <%= @user.name %></h1>
  <p>
    You have successfully signed up to TwitzNepal,
    your username is: <%= @user.username %>.<br>
    your password is: <%= @user.password %>
  </p>
  <p>Thanks for joining and have a great day!</p>
</body>
</html>

app/views/users/edit.html.erb
<div class="show">
  <div class="container">
    <div class="col-md-6">
      <div class="show-prof">
        <h2> Edit Profile</h2>
          <%=  form_for @user do |f| %>
             <% if @user.errors.any? %>
             <ul>
               <% @user.errors.full_messages.each do |e| %>
                  <li> <%= e %></li>
               <% end %>
             </ul>
             <% end %>
            <%= f.label :email, :for=>"nameField" %><br>
          <%= f.text_field :email, type: :email, :class=>"form-control"
           %>

          <%= f.label :name,:for=>"descField" %><br>
          <%= f.text_field :name, :class=>"form-control"
           %>

          <%= f.label :username, :for=>"usernameField" %><br>
          <%= f.text_field :username, :class=>"form-control" %>

          <%= f.label :password,:for=>"descField" %><br>
          <%=f.password_field :password, :class=>"form-control"
           %>

          <%= f.label :password_confirmation,:for=>"descfield" %><br>
          <%=f.password_field :password_confirmation , :class=>"form-control"
           %>
           <%= f.label :Avatar,:for=>"descfield" %><br>
          <%=f.file_field :avatar_url , :class=>"form-control"
           %>
            <%= f.label :bio,:for=>"descField" %><br>
          <%= f.text_area :bio, :class => "form-control text-area"%>
        <%= f.submit 'Update!!',:class=>"btn btn-success marg-5" %>
          <% end %>
      </div>
    </div>
  </div>
</div>
<%= javascript_include_tag 'twitzs' %>

app/views/users/friends.html.erb
<div class="show">
  <div class="container">
    <div class="col-md-6">
      <div class="show-prof">
       <h2>Friends' Twitz</h2>
         <% @twitzs.each do |twitz| %>
          <a href=" <%= user_path twitz.user %>">
            <img src="<%= twitz.user.avatar_url%>" class="img-responsive" alt="Image">
            <span><%= twitz.user.name %></span>
          </a>
          <span>@<%= twitz.user.username %></span>
          <span class="time"><%= time_ago_in_words(twitz.created_at) %>&nbsp;ago</span>
          <p>
            <%= twitz.content %>
          </p>
        <% end %>
      </div>
    </div>
    <div class=" col-md-offset-2 col-md-3">
     <% if current_user %>
      <h2>Create a Twitz</h2>
        <p>
        <%= form_for @twitz do |t| %>
        <%= t.text_area :content, :id=>"twitztxt",:class=>"text-area", :required=> true%>
        <%= t.submit "Twitz!!!", :class=>"btn btn-success marg-5", :id=> "twitzbtn" %>
        <span class="c-white" id="CharCount">0</span>
        <% end %>
      </p>
      <% end %>
    </div>
  </div>
</div>
<%= javascript_include_tag 'twitzs' %>

app/views/users/index.html.erb
<div class="show">
  <div class="container">
     <% if current_user %>
    <div class="col-md-3">
      <h2>Create a Twitz</h2>
        <p>
        <%= form_for @twitz do |t| %>
        <%= t.text_area :content, :id=>"twitztxt",:class=>"text-area", :required=> true%>
        <%= t.submit "Twitz!!!", :class=>"btn btn-success marg-5", :id=> "twitzbtn" %>
        <span class="c-white" id="CharCount">0</span>
        <% end %>
      </p>
      <% end %>
    </div>
    <div class="col-md-offset-2 col-md-6">
      <div class="show-prof">
       <h2>Public Profile</h2>
        <%@users.each do |user| %>
           <a href="<%= user_path user %>">
              <img src="<%= user.avatar_url%>" class="img-responsive" alt="Image">
              <span class="font-s"><%= user.name %></span>
            </a>
            <span>@<%= user.username %></span>
            <p>
              <%= user.twitzs.length %> Twitz
              <span class="spacing"><%= user.followers.length %>&nbsp;Followers</span>
              <span><%= user.followeds.length %>&nbsp;Following</span>
            </p>
            <% if user.bio  %>
                <p> <%= user.bio %></p>
            <% elsif user.twitzs.first %>
                <p> <%= user.twitzs.first.content %></p>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= javascript_include_tag 'twitzs' %>

app/views/users/new.html.erb
<div class="new-login">
  <div class="container">
    <div class="col-md-6 ">
      <img src="<%= asset_path('young-people.jpg') %>" class="img-responsive" alt="Image">
    </div>
    <div class="col-md-offset-1 col-md-5">
      <div class="login">
        <h3 class="c-white">New to TwitzNepal</h3>
        <%= form_for(@user) do |f| %>
        <% if @user.errors.any? %>
        <div id="error_explanation">
          <%= pluralize(@user.errors.count, "error") %>
          prohibited this product from being saved:
          <ul>
            <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
        <% end %>

        <%= f.label :email, :for=>"nameField" %><br>
        <%= f.text_field :email, type: :email, :class=>"form-control"
        %>

        <%= f.label :name,:for=>"descField" %><br>
        <%= f.text_field :name, :class=>"form-control"
        %>

        <%= f.label :username, :for=>"usernameField" %><br>
        <%= f.text_field :username, :class=>"form-control" %>

        <%= f.label :password,:for=>"descField" %><br>
        <%=f.password_field :password, :class=>"form-control"
        %>

        <%= f.label :password_confirmation,:for=>"descfield" %><br>
        <%=f.password_field :password_confirmation , :class=>"form-control"
        %>
        <%= f.submit 'Sign up',:class=>"btn btn-success marg-5" %>
        <%= button_tag "Reset", type: :reset, :class=>
        "btn btn-danger marg-5" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<!-- <div class="prof-backg marg-5">
      <img src="<%= asset_path('background.jpg') %>" class="img-responsive" alt="Image">
</div> -->
<div class="show">
  <div class="container">
    <div class="col-md-6">
      <div class="show-prof">
        <h2><%= @user.name %>'s TwitzNepal Profile
           <%= link_to("(Edit)", edit_user_path(@user)) if @user == current_user %>
        </h2>
        <img src="<%= @user.avatar_url%>" class="img-responsive" alt="Image">
        <span class="font-s"><%= @user.name %></span>
        <span>@<%= @user.username %></span>
        <p>
          <%= @user.twitzs.length %> Twitz
          <span class="spacing"><%= @user.followers.length %>&nbsp;Followers</span>
          <span><%= @user.followeds.length %>&nbsp;Following</span>
          <% if @user.bio %>
            <p> <%= @user.bio %></p>
          <% end %>
          <% if current_user && @user != current_user %>
            <% if current_user.following? @user %>
                <%= form_for @relationship, method: :delete do |f| %>
                    <%= f.submit "Unf ollow", :class=>"btn btn-success marg-5"  %>
                 <% end %>
            <% else %>
                 <%= form_for @relationship do |f| %>
                    <%= f.hidden_field :followed_id, value: @user.id %>
                    <%= f.submit "Follow", :class=>"btn btn-success marg-5"  %>
                 <% end %>
            <% end %>

          <% end %>
        </p>
      </div>
       <div class="show-prof marg-40">
          <h2>Twitz</h2>
          <div class="ribbitWrapper">
          <% @user.twitzs.each do |twitz| %>
                <img src="<%= twitz.user.avatar_url%>" class="img-responsive" alt="Image">
                <span class="font-s"><%= twitz.user.name %></span>
              <span>@<%= twitz.user.username %></span>
              <span class="time"><%= time_ago_in_words(twitz.created_at) %>&nbsp;ago</span>
              <p>
                <%= twitz.content %>
              </p>
            <% end %>
          </div>
        </div>
    </div>
    <% if current_user %>
    <div class="col-md-offset-2 col-md-3">
      <h2>Create a Twitz</h2>
        <p>
        <%= form_for @twitz do |t| %>
        <%= t.text_area :content, :id=>"twitztxt",:class=>"text-area", :required=> true%>
        <%= t.submit "Twitz!!!", :class=>"btn btn-success marg-5", :id=> "twitzbtn" %>
        <span class="c-white" id="CharCount">0</span>
        <% end %>
      </p>
      <% end %>
    </div>
  </div>
</div>
<%= javascript_include_tag 'twitzs' %>